### ISSUE TITLE
Multiple stored procedures, with the same code, in todos tables 

### ISSUE THREAD

**Issue by yoonghm** [meteor/postgres-packages#37] opened 2015-10-07 09:30 UTC
```
todos=# \d todos
                                    Table "public.todos"
   Column   |           Type           |                     Modifiers                      
------------+--------------------------+----------------------------------------------------
 id         | integer                  | not null default nextval('todos_id_seq'::regclass)
 created_at | timestamp with time zone | not null default now()
 list_id    | integer                  | not null
 text       | character varying(255)   | not null
 checked    | boolean                  | not null
Indexes:
    "todos_pkey" PRIMARY KEY, btree (id)
Triggers:
    "simple_pg_MjFR_todos" AFTER INSERT OR DELETE OR UPDATE ON todos FOR EACH ROW EXECUTE PROCEDURE "livequery_simple_pg_MjFR"()
    "simple_pg_cAnC_todos" AFTER INSERT OR DELETE OR UPDATE ON todos FOR EACH ROW EXECUTE PROCEDURE "livequery_simple_pg_cAnC"()
    "simple_pg_gCHo_todos" AFTER INSERT OR DELETE OR UPDATE ON todos FOR EACH ROW EXECUTE PROCEDURE "livequery_simple_pg_gCHo"()

todos=# \df+ "livequery_simple_pg_MjFR"
                                                                                                 List of functions
 Schema |           Name           | Result data type | Argument data types |  Type   | Security | Volatility | Owner | Language |                            Source code                             | Description 
--------+--------------------------+------------------+---------------------+---------+----------+------------+-------+----------+--------------------------------------------------------------------+-------------
 public | livequery_simple_pg_MjFR | trigger          |                     | trigger | invoker  | volatile   | spsy  | plpgsql  |                                                                   +| 
        |                          |                  |                     |         |          |            |       |          |   DECLARE                                                         +| 
        |                          |                  |                     |         |          |            |       |          |     row_data   RECORD;                                            +| 
        |                          |                  |                     |         |          |            |       |          |     full_msg   TEXT;                                              +| 
        |                          |                  |                     |         |          |            |       |          |     full_len   INT;                                               +| 
        |                          |                  |                     |         |          |            |       |          |     cur_page   INT;                                               +| 
        |                          |                  |                     |         |          |            |       |          |     page_count INT;                                               +| 
        |                          |                  |                     |         |          |            |       |          |     msg_hash   TEXT;                                              +| 
        |                          |                  |                     |         |          |            |       |          |   BEGIN                                                           +| 
        |                          |                  |                     |         |          |            |       |          |     IF (TG_OP = 'INSERT') THEN                                    +| 
        |                          |                  |                     |         |          |            |       |          |       SELECT                                                      +| 
        |                          |                  |                     |         |          |            |       |          |         TG_TABLE_NAME AS table,                                   +| 
        |                          |                  |                     |         |          |            |       |          |         TG_OP         AS op,                                      +| 
        |                          |                  |                     |         |          |            |       |          |         json_agg(NEW) AS data                                     +| 
        |                          |                  |                     |         |          |            |       |          |       INTO row_data;                                              +| 
        |                          |                  |                     |         |          |            |       |          |     ELSIF (TG_OP  = 'DELETE') THEN                                +| 
        |                          |                  |                     |         |          |            |       |          |       SELECT                                                      +| 
        |                          |                  |                     |         |          |            |       |          |         TG_TABLE_NAME AS table,                                   +| 
        |                          |                  |                     |         |          |            |       |          |         TG_OP         AS op,                                      +| 
        |                          |                  |                     |         |          |            |       |          |         json_agg(OLD) AS data                                     +| 
        |                          |                  |                     |         |          |            |       |          |       INTO row_data;                                              +| 
        |                          |                  |                     |         |          |            |       |          |     ELSIF (TG_OP = 'UPDATE') THEN                                 +| 
        |                          |                  |                     |         |          |            |       |          |       SELECT                                                      +| 
        |                          |                  |                     |         |          |            |       |          |         TG_TABLE_NAME AS table,                                   +| 
        |                          |                  |                     |         |          |            |       |          |         TG_OP         AS op,                                      +| 
        |                          |                  |                     |         |          |            |       |          |         json_agg(NEW) AS new_data,                                +| 
        |                          |                  |                     |         |          |            |       |          |         json_agg(OLD) AS old_data                                 +| 
        |                          |                  |                     |         |          |            |       |          |       INTO row_data;                                              +| 
        |                          |                  |                     |         |          |            |       |          |     END IF;                                                       +| 
        |                          |                  |                     |         |          |            |       |          |                                                                   +| 
        |                          |                  |                     |         |          |            |       |          |     SELECT row_to_json(row_data)::TEXT INTO full_msg;             +| 
        |                          |                  |                     |         |          |            |       |          |     SELECT char_length(full_msg)       INTO full_len;             +| 
        |                          |                  |                     |         |          |            |       |          |     SELECT (full_len / 7950) + 1       INTO page_count;           +| 
        |                          |                  |                     |         |          |            |       |          |     SELECT md5(full_msg)               INTO msg_hash;             +| 
        |                          |                  |                     |         |          |            |       |          |                                                                   +| 
        |                          |                  |                     |         |          |            |       |          |     FOR cur_page IN 1..page_count LOOP                            +| 
        |                          |                  |                     |         |          |            |       |          |       PERFORM pg_notify('simple_pg_MjFR',                         +| 
        |                          |                  |                     |         |          |            |       |          |         msg_hash || ':' || page_count || ':' || cur_page || ':' ||+| 
        |                          |                  |                     |         |          |            |       |          |         substr(full_msg, ((cur_page - 1) * 7950) + 1, 7950)       +| 
        |                          |                  |                     |         |          |            |       |          |       );                                                          +| 
        |                          |                  |                     |         |          |            |       |          |     END LOOP;                                                     +| 
        |                          |                  |                     |         |          |            |       |          |     RETURN NULL;                                                  +| 
        |                          |                  |                     |         |          |            |       |          |   END;                                                            +| 
        |                          |                  |                     |         |          |            |       |          |                                                                    | 
(1 row)

todos=# \df+ "livequery_simple_pg_cAnC"
                                                                                                 List of functions
 Schema |           Name           | Result data type | Argument data types |  Type   | Security | Volatility | Owner | Language |                            Source code                             | Description 
--------+--------------------------+------------------+---------------------+---------+----------+------------+-------+----------+--------------------------------------------------------------------+-------------
 public | livequery_simple_pg_cAnC | trigger          |                     | trigger | invoker  | volatile   | spsy  | plpgsql  |                                                                   +| 
        |                          |                  |                     |         |          |            |       |          |   DECLARE                                                         +| 
        |                          |                  |                     |         |          |            |       |          |     row_data   RECORD;                                            +| 
        |                          |                  |                     |         |          |            |       |          |     full_msg   TEXT;                                              +| 
        |                          |                  |                     |         |          |            |       |          |     full_len   INT;                                               +| 
        |                          |                  |                     |         |          |            |       |          |     cur_page   INT;                                               +| 
        |                          |                  |                     |         |          |            |       |          |     page_count INT;                                               +| 
        |                          |                  |                     |         |          |            |       |          |     msg_hash   TEXT;                                              +| 
        |                          |                  |                     |         |          |            |       |          |   BEGIN                                                           +| 
        |                          |                  |                     |         |          |            |       |          |     IF (TG_OP = 'INSERT') THEN                                    +| 
        |                          |                  |                     |         |          |            |       |          |       SELECT                                                      +| 
        |                          |                  |                     |         |          |            |       |          |         TG_TABLE_NAME AS table,                                   +| 
        |                          |                  |                     |         |          |            |       |          |         TG_OP         AS op,                                      +| 
        |                          |                  |                     |         |          |            |       |          |         json_agg(NEW) AS data                                     +| 
        |                          |                  |                     |         |          |            |       |          |       INTO row_data;                                              +| 
        |                          |                  |                     |         |          |            |       |          |     ELSIF (TG_OP  = 'DELETE') THEN                                +| 
        |                          |                  |                     |         |          |            |       |          |       SELECT                                                      +| 
        |                          |                  |                     |         |          |            |       |          |         TG_TABLE_NAME AS table,                                   +| 
        |                          |                  |                     |         |          |            |       |          |         TG_OP         AS op,                                      +| 
        |                          |                  |                     |         |          |            |       |          |         json_agg(OLD) AS data                                     +| 
        |                          |                  |                     |         |          |            |       |          |       INTO row_data;                                              +| 
        |                          |                  |                     |         |          |            |       |          |     ELSIF (TG_OP = 'UPDATE') THEN                                 +| 
        |                          |                  |                     |         |          |            |       |          |       SELECT                                                      +| 
        |                          |                  |                     |         |          |            |       |          |         TG_TABLE_NAME AS table,                                   +| 
        |                          |                  |                     |         |          |            |       |          |         TG_OP         AS op,                                      +| 
        |                          |                  |                     |         |          |            |       |          |         json_agg(NEW) AS new_data,                                +| 
        |                          |                  |                     |         |          |            |       |          |         json_agg(OLD) AS old_data                                 +| 
        |                          |                  |                     |         |          |            |       |          |       INTO row_data;                                              +| 
        |                          |                  |                     |         |          |            |       |          |     END IF;                                                       +| 
        |                          |                  |                     |         |          |            |       |          |                                                                   +| 
        |                          |                  |                     |         |          |            |       |          |     SELECT row_to_json(row_data)::TEXT INTO full_msg;             +| 
        |                          |                  |                     |         |          |            |       |          |     SELECT char_length(full_msg)       INTO full_len;             +| 
        |                          |                  |                     |         |          |            |       |          |     SELECT (full_len / 7950) + 1       INTO page_count;           +| 
        |                          |                  |                     |         |          |            |       |          |     SELECT md5(full_msg)               INTO msg_hash;             +| 
        |                          |                  |                     |         |          |            |       |          |                                                                   +| 
        |                          |                  |                     |         |          |            |       |          |     FOR cur_page IN 1..page_count LOOP                            +| 
        |                          |                  |                     |         |          |            |       |          |       PERFORM pg_notify('simple_pg_cAnC',                         +| 
        |                          |                  |                     |         |          |            |       |          |         msg_hash || ':' || page_count || ':' || cur_page || ':' ||+| 
        |                          |                  |                     |         |          |            |       |          |         substr(full_msg, ((cur_page - 1) * 7950) + 1, 7950)       +| 
        |                          |                  |                     |         |          |            |       |          |       );                                                          +| 
        |                          |                  |                     |         |          |            |       |          |     END LOOP;                                                     +| 
        |                          |                  |                     |         |          |            |       |          |     RETURN NULL;                                                  +| 
        |                          |                  |                     |         |          |            |       |          |   END;                                                            +| 
(1 row)
```

**Comment by rclai** [comment] 2015-10-07 12:42
Duplicate of #34.

**Comment by stubailo** [comment] 2015-10-07 17:07
Confirmed!

**Closed as completed by stubailo** 2015-10-07 17:07 UTC
